Mu.Schema.Lens package
higherkindness/mu-haskell pull request #227
Opened 2020-09-17 01:25 UTC by andremarianiello

I made this in an attempt to provide an equivalent to Mu.Schema.Optics, but for people who use `lens`. I will understand if you don't want it, but if you don't please let me know so that I can make it available some other way. Thanks!

2020-09-18 14:38 UTC, serras commented
The code looks OK, as far as I understand what's going on. However, when using it I get ambiguity errors all over the place. As an example, I've ported the `seed-server` applications to lens in the [`mu-lens` branch](https://github.com/higherkindness/mu-haskell/tree/mu-lens), assuming that `mu-lens` is to be used as `mu-optics`. Unfortunately I get about 5 of these:

```
/Users/serras/Projects/mu-haskell/examples/seed/src/Lens.hs:71:11: error:
    • Couldn't match type ‘Uninterpret r0’ with ‘'TPrimitive Text’
        arising from a use of ‘record’
      The type variable ‘r0’ is ambiguous
    • In the second argument of ‘($)’, namely ‘record (go w)’
      In the expression: pure $ record (go w)
      In an equation for ‘getWeather’:
          getWeather msg
            | Just w <- msg ^. #currentWeather = pure $ record (go w)
            | otherwise = pure $ record "who knows?"
            where ...
   |
71 |  = pure $ record (go w)
   |           ^^^^^^^^^^^^^
```

I might be doing something wrong by assuming that I can just copy the code that uses `mu-optics` unchanged, though.

2020-09-18 14:41 UTC, serras requested changes
I wrote some comments. In addition, would it be possible for you to run `stylish-haskell` with our custom set of rules in the `Lens.hs` file?

2020-09-18 16:27 UTC, andremarianiello commented
@serras I will take a look at those ambiguity errors to see if I can fix them. I'll handle the stylish-haskell formatting as well. Thanks for the feedback!

2020-09-20 19:03 UTC, andremarianiello commented
@serras One set of issues was handled by adding missing fundeps on the BuildRecord class, and one set was handled by adding a lens version of `is` from mu-optics. I cherry-picked your commit into my branch and included the fixes, and the example builds now.                                  Do you want me to add a version of the persistent-client-optics example as well?

2020-09-20 19:25 UTC, serras commented
@andremarianiello thanks for all your hard work! There's no need to update the other example (although we would not complain if you do, of course!). I'll review the code a bit more tomorrow, but I think it's ready to be merged :)

2020-09-21 08:34 UTC, kutyel commented on examples/seed/src/Lens.hs
> + where go e | e `is` #sunny  = "is sunny! 😄"
I think it looks way better this way! 🎉

2020-09-21 12:18 UTC, serras requested changes
The last tiny bit: could you use a explicit export for `Mu.Schema.Lens`?

2020-09-21 13:21 UTC, serras approved these changes
Awesome!

2020-09-21 13:24 UTC, merged